/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type PrizePosition = bigint;
export interface PrizeTier {
  'position' : PrizePosition,
  'prizeAmountUSD' : bigint,
}
export interface Team {
  'id' : TeamId,
  'captainName' : string,
  'name' : string,
  'rank' : [] | [bigint],
  'playerCount' : bigint,
  'tournamentId' : TournamentId,
  'kills' : bigint,
  'points' : bigint,
}
export type TeamId = bigint;
export interface Tournament {
  'id' : TournamentId,
  'status' : TournamentStatus,
  'name' : string,
  'description' : string,
  'gameMode' : string,
  'maxTeams' : bigint,
  'entryFee' : bigint,
  'startDate' : string,
}
export type TournamentId = bigint;
export type TournamentStatus = { 'upcoming' : null } |
  { 'completed' : null } |
  { 'ongoing' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createTournament' : ActorMethod<
    [string, string, string, string, bigint, bigint, TournamentStatus],
    TournamentId
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLeaderboard' : ActorMethod<[TournamentId], Array<Team>>,
  'getPrizePool' : ActorMethod<[TournamentId], Array<PrizeTier>>,
  'getRegisteredTeamsCount' : ActorMethod<[TournamentId], bigint>,
  'getTeamsForTournament' : ActorMethod<[TournamentId], Array<Team>>,
  'getTournament' : ActorMethod<[TournamentId], Tournament>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listTournaments' : ActorMethod<[], Array<Tournament>>,
  'registerTeam' : ActorMethod<[TournamentId, string, string, bigint], TeamId>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setPrizePool' : ActorMethod<[TournamentId, Array<PrizeTier>], undefined>,
  'updateTeamScore' : ActorMethod<[TeamId, bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];