/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TournamentStatus = IDL.Variant({
  'upcoming' : IDL.Null,
  'completed' : IDL.Null,
  'ongoing' : IDL.Null,
});
export const TournamentId = IDL.Nat;
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const TeamId = IDL.Nat;
export const Team = IDL.Record({
  'id' : TeamId,
  'captainName' : IDL.Text,
  'name' : IDL.Text,
  'rank' : IDL.Opt(IDL.Nat),
  'playerCount' : IDL.Nat,
  'tournamentId' : TournamentId,
  'kills' : IDL.Nat,
  'points' : IDL.Nat,
});
export const PrizePosition = IDL.Nat;
export const PrizeTier = IDL.Record({
  'position' : PrizePosition,
  'prizeAmountUSD' : IDL.Nat,
});
export const Tournament = IDL.Record({
  'id' : TournamentId,
  'status' : TournamentStatus,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'gameMode' : IDL.Text,
  'maxTeams' : IDL.Nat,
  'entryFee' : IDL.Nat,
  'startDate' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createTournament' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        TournamentStatus,
      ],
      [TournamentId],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLeaderboard' : IDL.Func([TournamentId], [IDL.Vec(Team)], ['query']),
  'getPrizePool' : IDL.Func([TournamentId], [IDL.Vec(PrizeTier)], ['query']),
  'getRegisteredTeamsCount' : IDL.Func([TournamentId], [IDL.Nat], ['query']),
  'getTeamsForTournament' : IDL.Func(
      [TournamentId],
      [IDL.Vec(Team)],
      ['query'],
    ),
  'getTournament' : IDL.Func([TournamentId], [Tournament], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listTournaments' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
  'registerTeam' : IDL.Func(
      [TournamentId, IDL.Text, IDL.Text, IDL.Nat],
      [TeamId],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setPrizePool' : IDL.Func([TournamentId, IDL.Vec(PrizeTier)], [], []),
  'updateTeamScore' : IDL.Func([TeamId, IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TournamentStatus = IDL.Variant({
    'upcoming' : IDL.Null,
    'completed' : IDL.Null,
    'ongoing' : IDL.Null,
  });
  const TournamentId = IDL.Nat;
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const TeamId = IDL.Nat;
  const Team = IDL.Record({
    'id' : TeamId,
    'captainName' : IDL.Text,
    'name' : IDL.Text,
    'rank' : IDL.Opt(IDL.Nat),
    'playerCount' : IDL.Nat,
    'tournamentId' : TournamentId,
    'kills' : IDL.Nat,
    'points' : IDL.Nat,
  });
  const PrizePosition = IDL.Nat;
  const PrizeTier = IDL.Record({
    'position' : PrizePosition,
    'prizeAmountUSD' : IDL.Nat,
  });
  const Tournament = IDL.Record({
    'id' : TournamentId,
    'status' : TournamentStatus,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'gameMode' : IDL.Text,
    'maxTeams' : IDL.Nat,
    'entryFee' : IDL.Nat,
    'startDate' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createTournament' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          TournamentStatus,
        ],
        [TournamentId],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLeaderboard' : IDL.Func([TournamentId], [IDL.Vec(Team)], ['query']),
    'getPrizePool' : IDL.Func([TournamentId], [IDL.Vec(PrizeTier)], ['query']),
    'getRegisteredTeamsCount' : IDL.Func([TournamentId], [IDL.Nat], ['query']),
    'getTeamsForTournament' : IDL.Func(
        [TournamentId],
        [IDL.Vec(Team)],
        ['query'],
      ),
    'getTournament' : IDL.Func([TournamentId], [Tournament], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listTournaments' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
    'registerTeam' : IDL.Func(
        [TournamentId, IDL.Text, IDL.Text, IDL.Nat],
        [TeamId],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setPrizePool' : IDL.Func([TournamentId, IDL.Vec(PrizeTier)], [], []),
    'updateTeamScore' : IDL.Func([TeamId, IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };